apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: skaffold-jupyter-lab
manifests:
  rawYaml:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: jupyterlab-svc
  address: 0.0.0.0
  port: 8888
  localPort: 8888
