apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-cm
data:
  jaas.conf: |
    KafkaServer {
      org.apache.kafka.common.security.scram.ScramLoginModule required
      username="admin"
      password="12345";
    };
    Client {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="internal"
      password="12345";
    };
  sasl_users_creation.sh: |
    /opt/kafka/bin/kafka-configs.sh --zookeeper zookeeper-svc:2181 --alter --add-config 'SCRAM-SHA-512=[iterations=4096,password=12345]' --entity-type users --entity-name user01;
    echo "done";
