apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skaffold-prometheus-grafana
deploy:
  kubectl:
    manifests:
    - grafana/statefulset.yaml
    - grafana/service.yaml
    - prometheus/configmap.yaml
    - prometheus/statefulset.yaml
    - prometheus/service.yaml
portForward:
- resourceType: service
  resourceName: grafana-svc
  port: 3000
  localPort: 3000
- resourceType: service
  resourceName: prometheus-svc
  port: 9090
  localPort: 9090
