apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-ha
  namespace: default
spec:
  replicas: 3
  image: rabbitmq:4.2-management-alpine
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  persistence:
    storageClassName: local-path
    storage: 20Gi
  # secretBackend:
  #   vault:
  #     role: rabbitmq
  #     annotations:
  #       vault.hashicorp.com/template-static-secret-render-interval: "15s"
  #     defaultUserPath: secret/data/rabbitmq/config
