apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  labels:
    app: rabbitmq
spec:
  ports:
  - name: web
    port: 15672
    protocol: TCP
    targetPort: 15672
  - name: listener
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq
