apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-rabbitmq
manifests:
  rawYaml:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: rabbitmq-svc
  port: 15672
  localPort: 15672
- resourceType: service
  resourceName: rabbitmq-svc
  port: 5672
  localPort: 5672
