apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-rabbitmq
manifests:
  rawYaml:
    - cluster.yaml
portForward:
- resourceType: service
  resourceName: rabbitmq-ha
  namespace: default
  port: 15672
  localPort: 15672
- resourceType: service
  resourceName: rabbitmq-ha
  namespace: default
  port: 5672
  localPort: 5672
