apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - image: wurstmeister/kafka:2.12-2.5.0
        name: kafka
        resources: {}
        ports:
        - containerPort: 29092
          name: internal
        - containerPort: 9092
          name: external
        securityContext:
          capabilities:
            add: [ "NET_ADMIN" ]
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        - name: KAFKA_ADVERTISED_LISTENERS
          value: INTERNAL://kafka-svc:29092,OUTSIDE://localhost:9092
        - name: KAFKA_LISTENERS
          value: INTERNAL://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
