apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  ports:
  - name: internal-port
    port: 29092
    protocol: TCP
    targetPort: 29092
  - name: external-port
    port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
