apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-cassandra
manifests:
  rawYaml:
    - statefulset.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: cassandra-svc
  port: 9042
  localPort: 9042
