apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-localstack
deploy:
  helm:
    releases:
      - name: localstack
        remoteChart: localstack-repo/localstack
        version: 0.6.24
        skipBuildDependencies: true
        #valuesFiles: [ values.yaml ]
