apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: ghcr.io/mealie-recipes/mealie:v3.0.1
        name: mealie
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: ALLOW_SIGNUP
          value: "false"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Monterrey"
        - name: BASE_URL
          value: "http://localhost"
        - name: DB_ENGINE
          value: "postgres"
        - name: POSTGRES_USER
          value: "mealie"
        - name: POSTGRES_PASSWORD
          value: "mealie"
        - name: POSTGRES_SERVER
          value: "postgres-svc"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "mealie"
