apiVersion: v1
kind: Service
metadata:
  name: redis-insight-svc
  labels:
    app: redis-insight
  namespace: default
spec:
  ports:
  - name: http
    port: 5540
    protocol: TCP
    targetPort: 5540
  selector:
    app: redis-insight
