apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-insight
  labels:
    app: redis-insight
  namespace: default
spec:
  replicas: 1
  serviceName: redis-insight-svc
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
      - image: redislabs/redisinsight:2.68.0
        name: redis-insight
        ports:
        - name: http
          containerPort: 5540
          protocol: TCP
        volumeMounts:
        - name: redis-insight-persist
          mountPath: /db
  volumeClaimTemplates:
  - metadata:
      name: redis-insight-persist
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 128Mi
