apiVersion: v1
kind: Service
metadata:
  name: smocker-svc
  labels:
    app: smocker
spec:
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: web
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: smocker
