apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skaffold-smocker
deploy:
  kubectl:
    manifests:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: smocker-svc
  address: 0.0.0.0
  port: 8080
  localPort: 8080
- resourceType: service
  resourceName: smocker-svc
  port: 8081
  localPort: 8081
