apiVersion: v1
kind: Service
metadata:
  labels:
    app: lldap-svc
  name: lldap-svc
spec:
  ports:
  - name: ldap
    port: 3890
    protocol: TCP
    targetPort: 3890
  - name: ui
    port: 17170
    protocol: TCP
    targetPort: 17170
  selector:
    app: lldap
