apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  mongo-init.js: |
    print("Creating User for HealthCheck");

    db.createUser({
      user: "healthCheck",
      pwd: "local",
      roles: [{ role: "read", db: "test" }],
    });

    print("Completed HealthCheck User creation");
