apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-mongodb
manifests:
  rawYaml:
    - statefulset.yaml
    - service.yaml
    - configmap.yaml
portForward:
- resourceType: service
  resourceName: mongodb-svc
  port: 27017
  localPort: 27017
