apiVersion: v1
kind: Service
metadata:
  labels:
    app: outline-wiki-svc
  name: outline-wiki-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: outline-wiki
