apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-harbor
deploy:
  helm:
    releases:
      - name: local-harbor
        remoteChart: harbor/harbor
        version: 1.9.0
        skipBuildDependencies: true
        valuesFiles: [ values.yaml ]
