apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: n8n
  name: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
      - image: n8nio/n8n:1.107.1
        name: n8n
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5678
        env:
        # - name: DB_TYPE
        #   value: "postgresdb"
        # - name: DB_POSTGRESDB_USER
        #   value: "n8n"
        # - name: DB_POSTGRESDB_PASSWORD
        #   value: "n8n"
        # - name: DB_POSTGRESDB_DATABASE
        #   value: "n8n"
        # - name: DB_POSTGRESDB_HOST
        #   value: "postgres-svc"
        # - name: DB_POSTGRESDB_PORT
        #   value: "5432"
        - name: GENERIC_TIMEZONE
          value: "America/Monterrey"
