deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2025-05-17
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          period: 24h
          prefix: index_
  storage:
    type: "filesystem"
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
singleBinary:
  replicas: 1
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0
chunksCache:
  enabled: false
test:
  enabled: false
lokiCanary:
  enabled: false
