prometheus:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
serverFiles:
  prometheus.yml:
    scrape_configs: []
server:
  extraFlags:
    - web.enable-lifecycle
    - web.enable-otlp-receiver
    # - web.enable-remote-write-receiver
alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
