deploymentMode: SimpleScalable
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
    - from: "2025-06-28"
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: loki_index_
        period: 24h
  storage:
    type: s3
    bucketNames:
      chunks: grafana-loki-chunks
      ruler: grafana-loki-ruler
      admin: grafana-loki-admin
    s3:
      endpoint: minio-hl.default.svc.cluster.local:9000
      region: null
      accessKeyId: <accessKeyId>
      secretAccessKey: <secretAccessKey>
      signatureVersion: null
      s3ForcePathStyle: true
      insecure: true
  ingester:
    chunk_encoding: snappy
  querier:
    max_concurrent: 4
  compactor:
    retention_enabled: true
    retention_delete_delay: 2h
    retention_delete_worker_count: 150
    delete_request_store: s3
  limits_config:
    retention_period: 672h # 28 days
    allow_structured_metadata: true
    volume_enabled: true
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
write:
  replicas: 1
  persistence:
    size: 10Gi
    storageClass: local-path
read:
  replicas: 1
  persistence:
    size: 10Gi
    storageClass: local-path
backend:
  replicas: 1
  persistence:
    size: 10Gi
    storageClass: local-path

singleBinary:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
chunksCache:
  enabled: false

test:
  enabled: false
lokiCanary:
  enabled: false
