apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-postgres
manifests:
  rawYaml:
    - statefulset.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: postgres-svc
  port: 5432
  localPort: 5432
