apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-redis
manifests:
  rawYaml:
    - redis/service.yaml
    - redis/statefulset.yaml
    - redisinsight/service.yaml
    - redisinsight/statefulset.yaml
portForward:
- resourceType: service
  resourceName: redis-svc
  port: 6379
  localPort: 6379
- resourceType: service
  resourceName: redis-insight-svc
  port: 8001
  localPort: 8001
