apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: skaffold-kafka
deploy:
  kubectl:
    manifests:
    - kafka/deploy.yaml
    - kafka/service.yaml
    - zookeeper/deploy.yaml
    - zookeeper/service.yaml
portForward:
- resourceType: service
  resourceName: kafka-svc
  port: 9092
  localPort: 9092
