apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocketbase
  labels:
    app: pocketbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocketbase
  template:
    metadata:
      labels:
        app: pocketbase
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: pocketbase:v0.28.1
        name: pocketbase
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
