apiVersion: v1
kind: Service
metadata:
  name: pocketbase-svc
  labels:
    app: pocketbase
spec:
  ports:
  - name: http
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: pocketbase
