apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: skaffold-pocketbase
deploy:
  kubectl:
    manifests:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: pocketbase-svc
  port: 8090
  localPort: 8090
