apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-pocketbase
manifests:
  rawYaml:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: pocketbase-svc
  port: 8090
  localPort: 8090
