apiVersion: skaffold/v3
kind: Config
metadata:
  name: skaffold-nexus
manifests:
  rawYaml:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: nexus-svc
  port: 8081
  localPort: 8081
