apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: skaffold-jetbrains-youtrack
manifests:
  rawYaml:
    - deploy.yaml
    - service.yaml
portForward:
- resourceType: service
  resourceName: youtrack-svc
  address: 0.0.0.0
  port: 8080
  localPort: 8080

